import type { Song, Playlist } from './types';

export const songs: Song[] = [
  {
    id: '1',
    title: 'Crimson Horizon',
    artist: 'The Vindicators',
    album: 'Echoes of Tomorrow',
    duration: 245,
    genre: 'Rock',
    year: 2022,
    coverArt: 'https://picsum.photos/seed/101/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  },
  {
    id: '2',
    title: 'Midnight Drive',
    artist: 'Night Cruisers',
    album: 'Neon Dreams',
    duration: 210,
    genre: 'Synthwave',
    year: 2021,
    coverArt: 'https://picsum.photos/seed/107/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
  },
  {
    id: '3',
    title: 'Summer Haze',
    artist: 'DJ Sol',
    album: 'Coastal Vibes',
    duration: 185,
    genre: 'Chillhop',
    year: 2023,
    coverArt: 'https://picsum.photos/seed/105/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
  },
  {
    id: '4',
    title: 'Lost in the Echo',
    artist: 'Static Bloom',
    album: 'Digital Garden',
    duration: 280,
    genre: 'Alternative',
    year: 2020,
    coverArt: 'https://picsum.photos/seed/108/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
  },
  {
    id: '5',
    title: 'Quantum Leap',
    artist: 'Galaxy Runners',
    album: 'Starlight',
    duration: 220,
    genre: 'Electronic',
    year: 2023,
    coverArt: 'https://picsum.photos/seed/103/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
  },
  {
    id: '6',
    title: 'Velvet Groove',
    artist: 'The Smooth Operators',
    album: 'Late Night Sessions',
    duration: 300,
    genre: 'Jazz',
    year: 2019,
    coverArt: 'https://picsum.photos/seed/104/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
  },
  {
    id: '7',
    title: 'Concrete Jungle',
    artist: 'Urban Pulse',
    album: 'City Soundscapes',
    duration: 195,
    genre: 'Hip Hop',
    year: 2022,
    coverArt: 'https://picsum.photos/seed/110/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
  },
  {
    id: '8',
    title: 'First Light',
    artist: 'Aura',
    album: 'Horizons',
    duration: 260,
    genre: 'Ambient',
    year: 2024,
    coverArt: 'https://picsum.photos/seed/102/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
  },
  {
    id: '9',
    title: 'Rebel Yell',
    artist: 'The Fuse',
    album: 'Ignition',
    duration: 180,
    genre: 'Punk',
    year: 2021,
    coverArt: 'https://picsum.photos/seed/109/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
  },
   {
    id: '10',
    title: 'Oceanic',
    artist: 'Deep Dive',
    album: 'Abyss',
    duration: 320,
    genre: 'Ambient',
    year: 2022,
    coverArt: 'https://picsum.photos/seed/105/400/400',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
  },
];

export const playlists: Playlist[] = [
  {
    id: 'pl-1',
    userId: 'user-1',
    name: 'Rock Anthems',
    description: 'All the rock hits that make you want to scream along.',
    songIds: ['1', '9', '4'],
    createdAt: '2023-10-26T10:00:00Z',
  },
  {
    id: 'pl-2',
    userId: 'user-1',
    name: 'Late Night Drive',
    description: 'Synthwave and electronic beats for cruising through the city after dark.',
    songIds: ['2', '5'],
    createdAt: '2023-11-15T18:30:00Z',
  },
  {
    id: 'pl-3',
    userId: 'user-1',
    name: 'Chill Focus',
    description: 'Lo-fi, chillhop, and ambient tunes to help you study or relax.',
    songIds: ['3', '8', '6', '10'],
    createdAt: '2024-01-05T09:00:00Z',
  },
  {
    id: 'pl-4',
    userId: 'user-1',
    name: 'Workout Beats',
    description: 'Up-tempo tracks to get you pumped for your workout.',
    songIds: ['7', '9', '1', '5'],
    createdAt: '2024-02-20T07:45:00Z',
  },
];
